

api:
  indicator:
    list_posts:
      name: Liste des posts
      url: https://jsonplaceholder.typicode.com/posts
    list_comments:
      name: Liste des commentaires
      url: https://jsonplaceholder.typicode.com/comments


